
# just check that all demos compile
all:
	cd demo_union       && make
	cd demo_voidpointer && make
	cd demo_untyped     && make
	cd demo_template    && make

run:
	cd demo_union       && make run
	cd demo_voidpointer && make run
	cd demo_untyped     && make run
	cd demo_template    && make run
